// Code generated by MockGen. DO NOT EDIT.
// Source: greeting.go
//
// Generated by this command:
//
//	mockgen -source=greeting.go -destination=mock_name_provider_test.go -package=greeting
//

// Package greeting is a generated GoMock package.
package greeting

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNameProvider is a mock of NameProvider interface.
type MockNameProvider struct {
	ctrl     *gomock.Controller
	recorder *MockNameProviderMockRecorder
	isgomock struct{}
}

// MockNameProviderMockRecorder is the mock recorder for MockNameProvider.
type MockNameProviderMockRecorder struct {
	mock *MockNameProvider
}

// NewMockNameProvider creates a new mock instance.
func NewMockNameProvider(ctrl *gomock.Controller) *MockNameProvider {
	mock := &MockNameProvider{ctrl: ctrl}
	mock.recorder = &MockNameProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNameProvider) EXPECT() *MockNameProviderMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockNameProvider) Name() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Name indicates an expected call of Name.
func (mr *MockNameProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockNameProvider)(nil).Name))
}
